name: Build and Release EXE

on:
  push:
    tags:
      - '*'

jobs:
  build-nuitka-exe:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install nuitka pillow

      - name: Build Executable
        run: python -m dsdultra build

      - name: Upload EXE to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/dsd.exe
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

  build-nuitka-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install nuitka pillow

      - name: Build Binary
        run: python -m dsdultra build

      - name: Upload Binary to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/dsd
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}